set_property PACKAGE_PIN D18 [get_ports {LED4bit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED4bit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED4bit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED4bit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED4bit[0]}]
set_property PACKAGE_PIN G14 [get_ports {LED4bit[2]}]
set_property PACKAGE_PIN M15 [get_ports {LED4bit[1]}]
set_property PACKAGE_PIN M14 [get_ports {LED4bit[0]}]
